### ISSUE TITLE
glad to see that

### ISSUE THREAD

**Issue by learningtime2025** [pehsa/ZFSguru2#3]
Do you know what happened with original project?

**Comment by karmantyu** [comment]
No clue. Ceased without warning! Maybe tragic accident or some other mishap occurred with the maintainers.

**Comment by learningtime2025** [comment]
do you have plans to make iso for installation?
also, that could be useful http://web.archive.org/web/20160331185019/http://zfsguru.com/doc/quick#manualfreebsdinstallationinstructions
